# Generated by Django 3.1.7 on 2021-02-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobre',
            name='descricao',
            field=models.TextField(default='', max_length=500, verbose_name='Descrição'),
        ),
    ]
