# Generated by Django 4.0.2 on 2024-01-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={},
        ),
        migrations.RemoveField(
            model_name='home',
            name='short',
        ),
    ]
