# Generated by Django 4.0.2 on 2024-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icone',
            field=models.CharField(choices=[('bxs-dashboard', 'dashboard'), ('bx-line-chart', 'gráfico'), ('bx-code-alt', 'developer')], default='bx-code-alt', max_length=15, verbose_name='Icone'),
        ),
    ]
