# Generated by Django 3.1.7 on 2021-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sobre_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='freela',
            field=models.BooleanField(default='Disponível', verbose_name='Disponível pra Freela?'),
        ),
    ]
