# Generated by Django 4.0.2 on 2024-01-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_home_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ativo',
        ),
    ]
