# Generated by Django 4.0.2 on 2024-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_services_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('cargo', models.CharField(max_length=300, verbose_name='Cargo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('period', models.CharField(max_length=300, verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Cargo',
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Education'},
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='expertise',
            new_name='education',
        ),
    ]
