# Generated by Django 3.1.7 on 2021-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(choices=[('Educação', 'Educação'), ('Experiência', 'Experiência')], max_length=12, verbose_name='Título')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ano', models.CharField(default='2020-2021', max_length=9, verbose_name='Ano')),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('icon-graduation', 'Chapéu'), ('icon-briefcase', 'Maleta')], max_length=15, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'resumo',
                'verbose_name_plural': 'resumos',
            },
        ),
    ]
