# Generated by Django 4.0.2 on 2024-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_jobs_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='education',
            field=models.CharField(max_length=300, verbose_name='Educação'),
        ),
    ]
