# Generated by Django 3.1.7 on 2021-03-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resumo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resumo',
        ),
    ]
