# Generated by Django 4.0.2 on 2024-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_services_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icone',
            field=models.CharField(choices=[('bxs-dashboard', 'dashboard'), ('bx-line-chart', 'gráfico'), ('bx-code-alt', 'developer')], default='bx-code-alt', max_length=20, verbose_name='Icone'),
        ),
    ]
