# Generated by Django 4.0.2 on 2024-02-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_portfolio_options_remove_portfolio_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Projeto'),
        ),
    ]
